CREATE DATABASE eric_system;
CREATE DATABASE carol_gabi_melissa;
CREATE DATABASE caetano_sara;
CREATE DATABASE gabriel_felipe;
CREATE DATABASE julia_felipe_thyago;
CREATE DATABASE juliana_matheus;
CREATE DATABASE laura_mariaclara_balestre;
CREATE DATABASE masrcos_igor_rafael;

USE login_register_system;
USE carol_gabi_melissa;
USE gabriel_felipe;
USE julia_felipe_thyago;
USE juliana_matheus;
USE laura_mariaclara_balestre;
USE masrcos_igor_rafael;
USE caetano_sara;

CREATE TABLE users(
user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
user_name VARCHAR(100) NOT NULL,
user_email VARCHAR(100) NOT NULL,
user_password VARCHAR(255) NOT NULL,
user_date DATETIME NOT NULL
);


USE login_register_system;

CREATE TABLE user_images(
user_image_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
user_image_name VARCHAR(255) NOT NULL,
user_image_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);




















UPDATE user_images SET user_image_name = "/1730111054410-855004170_dubstep.jpg" WHERE user_image_id = 5;

DROP TABLE user_images;

SELECT * FROM users;
SELECT * FROM user_images;

DELETE FROM user_images WHERE user_image_id = 1;
DELETE FROM user_images WHERE user_image_id = 2;
DELETE FROM user_images WHERE user_image_id = 3;

CREATE TABLE admin_users(
admin_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
admin_name VARCHAR(100) NOT NULL,
admin_email VARCHAR(100) NOT NULL,
admin_password VARCHAR(255) NOT NULL,
admin_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE admin_users;

SELECT * FROM admin_users;

INSERT INTO admin_users(admin_name, admin_email, admin_password, admin_date)
VALUES('Eric Gregorio', 'gregorio.eric@gmail.com', 'FR$5tghy6',  NOW());

SELECT * FROM admin_users WHERE admin_email = "eric@eric.com";

DELETE FROM admin_users WHERE admin_id = 1;

CREATE TABLE books(
book_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
book_image VARCHAR(255) NOT NULL,
book_name VARCHAR(180) NOT NULL,
book_autor VARCHAR(255) NOT NULL,
book_categoria VARCHAR(255) NOT NULL,
book_desc TEXT NOt NULL,
book_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE books;
SELECT * FROM books;

-- MySQL Script generated by MySQL Workbench
-- Mon Sep 23 20:02:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `position` (
  `position_id` INT NOT NULL AUTO_INCREMENT,
  `position_name` VARCHAR(100) NOT NULL,
  `position_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`position_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pages` (
  `page_id` INT NOT NULL AUTO_INCREMENT,
  `page_title` VARCHAR(180) NOT NULL,
  `page_status` TINYINT(0) NOT NULL,
  `page_content` TEXT NOT NULL,
  `page_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `position_position_id` INT NOT NULL,
  PRIMARY KEY (`page_id`),
  INDEX `fk_pages_position_idx` (`position_position_id` ASC) VISIBLE,
  CONSTRAINT `fk_pages_position`
    FOREIGN KEY (`position_position_id`)
    REFERENCES `position` (`position_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

DROP TABLE pages;
DROP TABLE position;
SELECT * FROM pages;

SELECT * FROM position;

INSERT INTO position (position_name, position_date) VALUES ('Home section one', NOW());
INSERT INTO position (position_name, position_date) VALUES ('Sobre Nós', NOW());
INSERT INTO position (position_name, position_date) VALUES ('Serviços', NOW());
INSERT INTO position (position_name) VALUES ('Home Section One');
INSERT INTO position (position_name) VALUES ('Home Section Two');



SELECT p.page_id, p.page_title, p.page_status, p.page_content, p.page_date, pos.position_name, pos.position_date
FROM login_register_system.pages p
JOIN login_register_system.position pos 
ON p.position_position_id = pos.position_id;

UPDATE pages SET page_title = ?, page_status = ?, page_content = ?, position_position_id = ? WHERE page_id = ?;

INSERT INTO login_register_system.pages (page_title, page_status, page_content, page_date, position_position_id)
VALUES 
    ('Título da Página', 1, 'Conteúdo da página aqui...', NOW(), 1);


SELECT pages.page_id,
                               pages.page_title,
                               pages.page_status,
                               pages.page_content,
                               position.position_id,
                               position.position_name
                           FROM 
                               pages
                           JOIN
                               position
                               ON pages.position_position_id = position.position_id
                           WHERE
                               pages.page_id = ?;


SELECT * FROM users WHERE user_email = 'greogrio.eric@gmail.com';