SELECT * FROM books;
SELECT * FROM alunos;
SELECT * FROM books;

ALTER TABLE books ADD book_slug VARCHAR(255);
ALTER TABLE books MODIFY COLUMN book_slug VARCHAR(255) AFTER book_desc;

-- MySQL Script generated by MySQL Workbench
-- Wed Oct 23 02:23:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `carol_gabi_melissa`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carol_gabi_melissa`.`alunos` (
  `aluno_id` INT NOT NULL AUTO_INCREMENT,
  `aluno_name` VARCHAR(120) NOT NULL,
  `aluno_email` VARCHAR(120) NOT NULL,
  `aluno_serie` VARCHAR(10) NOT NULL,
  `aluno_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`aluno_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carol_gabi_melissa`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carol_gabi_melissa`.`books` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `book_image` VARCHAR(255) NOT NULL,
  `book_name` VARCHAR(120) NOT NULL,
  `book_autor` VARCHAR(100) NOT NULL,
  `book_categoria` VARCHAR(100) NOT NULL,
  `book_desc` TEXT NOT NULL,
  `book_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login_register_system`.`loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carol_gabi_melissa`.`loan` (
  `loan_id` INT NOT NULL AUTO_INCREMENT,
  `books_book_id` INT NOT NULL,
  `alunos_aluno_id` INT NOT NULL,
  `loan_date_atual` DATE NOT NULL,
  `loan_date_entrega` DATE NOT NULL,
  `loan_date_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`loan_id`),
  INDEX `fk_loan_books_idx` (`books_book_id` ASC) VISIBLE,
  INDEX `fk_loan_alunos1_idx` (`alunos_aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_loan_books`
    FOREIGN KEY (`books_book_id`)
    REFERENCES `carol_gabi_melissa`.`books` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loan_alunos1`
    FOREIGN KEY (`alunos_aluno_id`)
    REFERENCES `carol_gabi_melissa`.`alunos` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- DROP TABLE loan;
-- DROP TABLE books;
-- DROP TABLE alunos;

SELECT * FROM books;

SELECT 
  alunos.aluno_id,
  alunos.aluno_name,
  alunos.aluno_email,
  alunos.aluno_serie,
  books.book_id,
  books.book_name,
  books.book_autor,
  books.book_categoria,
  loan.loan_id,
  loan.loan_date_atual,
  loan.loan_date_entrega
FROM 
  carol_gabi_melissa.loan
JOIN 
  carol_gabi_melissa.alunos ON loan.alunos_aluno_id = alunos.aluno_id
JOIN 
  carol_gabi_melissa.books ON loan.books_book_id = books.book_id;

UPDATE books SET book_image = '/1730747727992-577264565_corpos_secos.jpg' WHERE book_id = 1;
