DROP DATABASE IF NOT EXISTS login_register_system;

CREATE DATABASE IF NOT EXISTS login_register_system;

USE login_register_system

CREATE TABLE users( 
user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
user_name VARCHAR(120) NOT NULL,
user_email VARCHAR(120) NOT NULL,
user_password VARCHAR(255) NOT NULL,
user_date DATETIME NOT NULL
);


CREATE TABLE admin_users( 
admin_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
admin_name VARCHAR(120) NOT NULL,
admin_email VARCHAR(120) NOT NULL,
admin_password VARCHAR(255) NOT NULL,
admin_date DATETIME NOT NULL
);

-- MySQL Script generated by MySQL Workbench
-- Fri Oct 25 18:37:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema login_register_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema login_register_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `login_register_system` DEFAULT CHARACTER SET utf8 ;
USE `login_register_system` ;

-- -----------------------------------------------------
-- Table `login_register_system`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_register_system`.`position` (
  `position_id` INT NOT NULL AUTO_INCREMENT,
  `position_name` VARCHAR(100) NOT NULL,
  `position_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`position_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login_register_system`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_register_system`.`pages` (
  `page_id` INT NOT NULL AUTO_INCREMENT,
  `page_title` VARCHAR(180) NOT NULL,
  `page_status` TINYINT(0) NOT NULL,
  `page_content` LONGTEXT NOT NULL,
  `page_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `position_position_id` INT NOT NULL,
  PRIMARY KEY (`page_id`),
  INDEX `fk_pages_position_idx` (`position_position_id` ASC) VISIBLE,
  CONSTRAINT `fk_pages_position`
    FOREIGN KEY (`position_position_id`)
    REFERENCES `login_register_system`.`position` (`position_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login_register_system`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_register_system`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(120) NOT NULL,
  `user_email` VARCHAR(120) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
